yy-map:
  #百度api相关参数
  output: json
  ak: YXGMpZebN4WsctI7X2eoysoNPwI55lFz

server:
  port: 8692

spring:
  application:
    name: yy-map
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
