security:
  ignore:
    whites: #白名单列表
      - /user/login
server:
  port: 10010
spring:
  application:
    name: gateway #服务名
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
    gateway:
      #跨域配置
      globalcors:
        add-to-simple-url-handler-mapping: true #解决 options 请求被拦截问题
        cors-configurations:
          '[/**]':
            allowed-origins: #允许哪些网站的跨域请求
              - "http://localhost:8099"
            allowed-methods: #允许的跨域 ajax 的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowed-headers: "*" #允许在请求头中携带的头信息
#            allowed-credentials: true #是否允许携带cookie
            max-age: 360000 #这次跨域检测的有效期
      #网关路由配置
      routes:
        - id: yy-user #路由id，自定义，只要唯一即可
          uri: lb://yy-user #路由的目标地址，lb是负载均衡，后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** #这个是按照路径匹配，只要以/user/开头就符合要求
        - id: yy-delicacy
          uri: lb://yy-delicacy
          predicates:
            - Path=/delicacy/**,/delicacyUser/**,/foodType/**,/static/**
        - id: yy-map
          uri: lb://yy-map
          predicates:
            - Path=/map/**